name: cocktail-app

services:
  api:
    build: ./be/
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../backend:/src/backend/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/docker/volumes/pgdata/_data
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$(cat $${POSTGRES_DB_FILE}) -U $$(cat $${POSTGRES_USER_FILE})"]
      interval: 1s
      timeout: 5s
      retries: 10
    secrets:
      - db_name
      - db_user
      - db_pass

volumes:
  pgdata:
    external: true

secrets:
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_pass:
    file: ./secrets/db_pass