name: cocktail-app

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d/
    depends_on:
      - web
    networks:
      - dev

  web:
    build:
      context: ../frontend/
      target: dev
    restart: unless-stopped
    volumes:
      - ../frontend:/src/
      - /src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - dev

  api:
    build:
      context: ../backend/
    restart: unless-stopped
    volumes:
      - ../backend:/src/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - dev

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$(cat $${POSTGRES_DB_FILE}) -U $$(cat $${POSTGRES_USER_FILE})"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    secrets:
      - db_name
      - db_user
      - db_pass
    networks:
      - dev

volumes:
  pgdata:
    external: true

secrets:
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_pass:
    file: ./secrets/db_pass

networks:
  dev:
    driver: bridge
